proxy:
  bind: '127.0.0.1'
  protocols:
    http: 8880
  modules:
    [ 
        {
          name: 'serialize',
          path: 'modules.serialize',
          run_contexts: ['request', 'response'],
          kwargs: {}
        },
        { name: 'addLag',
          path: 'modules.addLag',
          run_contexts: ['request'],
          kwargs: { minimum: 1, maximum: 5, }
        }
    ]
upstream:
  address: '127.0.0.1'
  port: 9980



