proxy:
  bind_address: '127.0.0.1'

  protocols:
    http: 8880

  upstream:
    address: '127.0.0.1'
    port: 8080

mgmt:
  tcp:
    address: '127.0.0.1'
    port: 5150
  redis:
    address: '127.0.0.1'
    port: 6379
    request_channel: 'proxy_mgmt_request'
    response_channel: 'proxy_mgmt_response'
  log:
    path: '{}/logs/run.log'
    standard_out: 'yes'
